Replace old scope selector with new one based on mui
Orckestra/orc-shared pull request #186
Opened 2021-01-26 18:35 UTC by Crispried

2021-01-26 22:58 UTC, Anstsiya approved these changes

2021-01-27 07:07 UTC, InnaBoitsun requested changes

2021-01-27 11:39 UTC, Crispried commented on src/components/MaterialUI/DataDisplay/CollapsableList.test.js
> +  const defaultElement = <p>Item1</p>;
It looks like different tab size. I've put to our prettier config rule that tabs should have size 2.

2021-01-27 13:32 UTC, Anstsiya approved these changes

2021-01-27 13:40 UTC, merged