Added support for multi modules application
Orckestra/orc-shared pull request #449
Opened 2021-11-04 16:42 UTC by joclefrancois

Story: AB#53620

2021-11-04 17:42 UTC, TONYFECTEAU approved these changes

2021-11-06 04:42 UTC, TONYFECTEAU submitted a review, later dismissed

2021-11-08 15:36 UTC, orck-adrouin requested changes

2021-11-08 15:36 UTC, orck-adrouin commented on src/components/Modules.js
> +	}, [isHidden, moduleInfo, dispatch, id, scopeFromRoute, applicationModules]);
will moduleInfo always be different here?

2021-11-08 15:36 UTC, orck-adrouin commented on src/components/Modules.js
> +	}, [dispatch, history, moduleInfo, currentRoute]);
ditto

2021-11-08 15:36 UTC, orck-adrouin commented on src/reducers/scopes.js
> +					} else console.log("a");
ah ha!

2021-11-08 15:36 UTC, orck-adrouin commented on src/reducers/scopes.js
> +						} else console.log("a");
b!

2021-11-08 15:50 UTC, joclefrancois commented on src/components/AppFrame/MenuItem.js
>  	hide,
Nowhere, but if I remove the prop, React will complain as it could be part of the module object.

2021-11-09 15:18 UTC, orck-adrouin commented on src/components/AppFrame/MenuItem.js
>  	hide,
test

2021-11-09 15:20 UTC, joclefrancois commented on src/components/AppFrame/MenuItem.js
>  	hide,
Warning: Invalid value for prop `hide` on <a> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://fb.me/react-attribute-behavior.

2021-11-09 15:38 UTC, orck-adrouin submitted a review, later dismissed

2021-11-09 15:46 UTC, orck-adrouin approved these changes

2021-11-09 15:52 UTC, merged