fixed date time zone
Orckestra/orc-shared pull request #468
Opened 2022-04-04 12:26 UTC by OlyaAn

2022-04-04 12:34 UTC, TONYFECTEAU approved these changes

2022-04-04 16:36 UTC, InnaBoitsun requested changes

2022-04-04 16:36 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
> +		console.log(timezone);
remove console.log
and move this methods to timezoneHelper and cover with tests

2022-04-04 16:36 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
> +						selected={startDate ? setLocalZone(startDate, getTimeZoneByName(timePickerTimeZone)) : null}
set correct value where the startDate calculated, on line #138

2022-04-04 16:36 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
>  		}
overwrite local timezone just when custom timezone is specified and time is used for picker, not always

2022-04-05 07:16 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
> +	const startDate = value ? setLocalZoneDate(new Date(value), getTimeZoneByName(timePickerTimeZone)) : null;
define and calculate timeZoneName once and then use
const timeZoneName = getTimeZoneByName(timePickerTimeZone);

2022-04-05 08:13 UTC, InnaBoitsun commented on src/utils/timezoneHelper.js
> +export const setOtherZoneDate = (date, timezone) => {
let rename to convertTimeToOtherTimeZone    and add some sammary

2022-04-05 08:14 UTC, InnaBoitsun commented on src/utils/timezoneHelper.js
> +export const setLocalZoneDate = (date, timezone) => {
et rename to convertTimeToLocalTimeZone and add some summary

2022-04-05 11:42 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
> +			}
can be simplified like this?
```
if (onChange) {
   onChange((useTime && timePickerTimeZone) ? convertTimeToOtherTimeZone(date, timeZoneName) : date, metadata);
}
```

2022-04-05 11:46 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.js
> +	const startDate = value ? convertTimeToLocalTimeZone(new Date(value), timeZoneName) : null;
do we need to convert when timePickerTimeZone is undefined?

2022-04-05 14:21 UTC, InnaBoitsun approved these changes

2022-04-05 14:21 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.test.js
> +		const onChangeMock = jest.fn();
is the test name corresponding what it is doing?

2022-04-05 14:21 UTC, InnaBoitsun commented on src/components/MaterialUI/Inputs/DatePicker.test.js
> +	it("should call onChange prop with timezone without value", () => {
is the test name corresponding what it is doing?

2022-04-06 06:12 UTC, InnaBoitsun approved these changes

2022-04-06 06:18 UTC, merged